### PR TITLE
From SweepAI

### PR DESCRIPTION
**Pull request by MeDott29**

### CODE REVIEW

**Comment by dadukhankevin** [comment]
Hey, thanks for the pull request!
Any chance you could provide just a quick summary of what you've added and what all the .yaml files are intended to provide from `sweep-ai[bot]`?

**Comment by MeDott29** [comment]
sweep.yml is a config file for Sweep, like a system message.

[SweepAI](https://sweep.dev/) is worth checking out.  I started using it about a week ago.  It's one of the best Generative AI coding tools I've found.

I'm trying to experiment and find a good way to learn this library and contribute.  This pull request is a mess in part because there are too many unrelated additions.  Thanks for not closing it right away.

Would you be willing to do a video call explaining what you're doing?  I want to learn about this library. 
Also, I think if you want to present your work to a wider audience, a video presentation is the way to go.  Our call could serve as a first draft of a project explanation video.

**Comment by MeDott29** [comment]
Exaptation refers generally to a trait, characteristic, or feature being used for a purpose other than the one it was initially intended for Source 0. It's a term borrowed from evolutionary biology where it describes a feature that evolves for one purpose but later gets co-opted for a different use.

**Comment by MeDott29** [comment]
I know very little about what you're doing with Finch apart from what I've intuited from your Twitter posts and skimming the repo.  I'm intensely interested in my conception of what you're doing with Finch because I think you're driving at something fundamental, powerful and useful.

I think the concept of evolutionary algorithms are part of being able to accomplish a lot more from one text prompt.
How do I trick SweepAI into doing what I want it to?  How do I trick x into doing y?

**Comment by dadukhankevin** [comment]
@MeDott29 Awesome, I'd love to talk with you at some point, and you're definitely right about a video presentation (idk why I never thought of that).
I'm pretty busy at least this next week but maybe after that?
In the meantime, I'll try and add reviews to this PR and hopefully, we can get it merged soon, it just might take a bit of time since I'm a bit swamped with school atm. I'm super encouraged that you're interested in Finch, literally means the world!

**Pull request closed without merging**
